### ISSUE TITLE
Aplikacja testowa obsługi 2 ekranów - Aplikacja desktopowa Avalonia UI

### ISSUE THREAD

**Issue by BartShoot** [Lorn-Hukka/info-kiosk#1]
- [x] Tworzenie dwóch okien
- [x] Ustawienie pełnego ekranu bez pasków
- [x] Wybranie odpowiedniego monitora dla okna odpowiadającego za input
- [ ] Input i odświeżanie obu widoków po naciśnięciu

**Comment by Lorn-Hukka** [comment]
Testy skończone.
