### ISSUE TITLE
Aplikacja testowa obsługi 2 ekranów - Aplikacja desktopowa .NET MAUI

### ISSUE THREAD

**Issue by BartShoot** [Lorn-Hukka/info-kiosk#3]
- [x] Tworzenie dwóch okien
- [ ] Ustawienie pełnego ekranu bez pasków
- [ ] Wybranie odpowiedniego monitora dla okna odpowiadającego za input
- [x] Input i odświeżanie obu widoków po naciśnięciu

**Comment by mjakobsche** [comment]
Brak możliwości spełnienia wszystkich punktów w określonej technologii.  Prototyp przesłany na stosownego brancha
